MainApp/urls.py
from unicodedata import name
from django.urls import path

from. import views

app_name ='MainApp'

urlpatterns =[
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name= 'pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment, name='new_comment'),
]

pizzeria_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),

]

urlpatterns += staticfiles_urlpatterns()

MainApp/models.py
from tkinter import CASCADE
from django.db import models

# Create your models here.

class Pizza(models.Model):
    pizza_name= models.CharField(max_length=100)
    date_added =models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    Pizza =models.ForeignKey(Pizza,on_delete=models.CASCADE)
    topping_name= models.TextField(max_length=200)

    class Meta:
        verbose_name_plural= 'Topping'

    def __str__(self):
        return self.topping_name

MainApp/forms.py
from django import forms

from.models import Topping


class PizzaForm(forms.ModelForm):
    class Meta:
        Model = Topping
        fields = ['text']
        labels = {'text':''}

MainApp/views.py
from django.shortcuts import render,redirect
from .models import Pizza, Topping
from .forms import PizzaForm

# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html')

def pizzas(request):
    pizzas =Pizza.objects.all()

    context ={'pizzas': pizzas} #key for html value for views

    return render(request,'MainApp/pizzas.html',context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings =pizza.topping_set.order_by('-topping_name')

    context= {'pizza':pizza,'toppings':toppings}
    return render(request,'MainApp/pizza.html',context)

def new_comment(request, pizza_id):

    pizza = Topping.objects.get(id=pizza_id)

    if request.method !='POST':
        form = PizzaForm()
    else:
        form =PizzaForm(data=request.POST)

        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.pizza= pizza
            new_comment.save()
            return redirect('MainApp:pizza',pizza_id=pizza_id)

    context= {'form':form,'pizza':pizza}
    return render(request,'MainApp/new_comment.html',context)

MainApp/templates/mainapp/base.html
<p>

    <a href="{% url 'MainApp:index' %}">Home Page</a>


    <a href="{% url 'MainApp:pizzas' %}">Available Pizzas</a>




</p>

{% block content %}

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}

{% block content %}
<h1>Welcome to the Pizzeria</h1>
<p>
Here you will find the waco's best pizza 
</p>
<p> {% load static %} <img src="{% static "dj_app/media/image.jpg" %}" alt="index" /> </p>


{% endblock content %}

MainApp/templates/mainapp/new_comment.html
{% extends "MainApp/base.html" %}

{% block content %}


<p><a href="{% url 'MainApp:pizza' pizza.id %}">{{ pizza }}</a></p>
<p>Add a new comment:</p>

<form action="{% url 'MainApp:new_comment' pizza.id %}" method='post'>
    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Add comment</button>

</form>



{% endblock content %}

MainApp/templates/mainapp/pizza.html
{% extends "MainApp/base.html" %}

{% block content %}

<p>
    Pizza: {{ pizza }}


</p>

<ul>
    {% for topping in toppings %}
    <li>
        <p>Toppings list</p>
        <p>{{ topping}}</p>
    </li>
    {% empty %}
    <li>There are no toppings for this post yet.</li>
    {% endfor %}
</ul>
<p>
<a href="{% url 'MainApp:new_comment' pizza.id %}">Add a new comment</a>
</p>


{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% extends "MainApp/base.html" %}

{% block content %}


<P>Click the links below for topping detail</P>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'MainApp:pizza' pizza.id %}">{{pizza}}</a>

    
    </li>
    {% empty %}
    <li>No Pizza have been added yet.</li>
    {% endfor %}
</ul>
<p> {% load static %} <img src="{% static "dj_app/media/HawaiianPizza.jpg" %}" alt="index" /> </p>

<p> {% load static %} <img src="{% static "dj_app/media/BBQChicken.jpg" %}" alt="index" /> </p>

<p> {% load static %} <img src="{% static "dj_app/media/Pepperoni.jpg" %}" alt="index" /> </p>




{% endblock content %}